saved 2024-02-27 09:52:27

diff --git a/release/action.yml b/release/action.yml
--- a/release/action.yml
+++ b/release/action.yml
@@ -21,15 +21,15 @@ runs:
       with:
         export-env: false
       env:
-        id: op://Integrations/ssh-keypair.bot_kamaranl.vip/private-ke
-        id_pub: op://Integrations/ssh-keypair.bot_kamaranl.vip/public-ke
+        id: op://Integrations/ssh-keypair.bot_kamaranl.vip/private-key
+        id_pub: op://Integrations/ssh-keypair.bot_kamaranl.vip/public-key
       id: op-ssh
 
     - if: |
         fromJson(steps.checks.outputs.git).has-keypair == false &&
             ( steps.op-ssh.outputs.id == null ||
               steps.op-ssh.outputs.id_pub == null )
-      run: echo "::notice::Failed to load ssh id from previous action"; exit 128
+      run: echo "::error::Failed to load ssh keypair from previous action"; exit 128
       shell: bash
 
     - if: |
@@ -80,11 +80,11 @@ runs:
       shell: bash
       id: commit
 
-    - if: steps.commit.outputs == null
-      run: echo "::notice::git did not commit successfully, exiting now"; exit 128
+    - if: steps.commit.outputs.tag == null
+      run: echo "::error::Failed to commit changes"; exit 128
       shell: bash
 
-    - if: steps.commit.outputs
+    - if: steps.commit.outputs.tag
       run: |
         : # create tag
         echo "::debug::tag($CI_TAG)"
