saved 2024-02-22 15:21:22

diff --git a/checks/action.yml b/checks/action.yml
--- a/checks/action.yml
+++ b/checks/action.yml
@@ -1,9 +1,9 @@
 name: 'checks'
 description: ''
 inputs:
-  checks:
+  check:
     description: |
-      {timezone,gh_token,repository}
+      [string[]] {timezone,gh_token,repository,tags_releases,all}
 
       Default: 'all'
     default: 'all'
@@ -18,11 +18,14 @@ outputs:
   repository:
     value: ${{ steps.repository.outputs.check }}
     description: ''
+  tags_releases:
+    value: ${{ steps.tags_releases.outputs.check }}
+    description: ''
 
 runs:
   using: composite
   steps:
-    - if: contains(inputs.checks, 'timezone') || inputs.checks == 'all'
+    - if: contains(inputs.check, 'timezone') || inputs.check == 'all'
       run: |
         {
             [ "$(</etc/timezone)" != "America/New_York" ] &&
@@ -31,7 +34,7 @@ runs:
       shell: bash
       id: timezone
 
-    - if: contains(inputs.checks, 'gh_token') || inputs.checks == 'all'
+    - if: contains(inputs.check, 'gh_token') || inputs.check == 'all'
       run: |
         {
             [ -z "$GH_TOKEN" ] &&
@@ -40,7 +43,7 @@ runs:
       shell: bash
       id: gh_token
 
-    - if: contains(inputs.checks, 'repository') || inputs.checks == 'all'
+    - if: contains(inputs.check, 'repository') || inputs.check == 'all'
       run: |
         {
             ! git status >/dev/null 2>&1 &&
@@ -48,3 +51,13 @@ runs:
         }; :
       shell: bash
       id: repository
+
+    - if: contains(inputs.check, 'tags_releases') || inputs.check == 'all'
+      run: |
+        {
+            if ! git describe --tags --abbrev=0 >/dev/null 2>&1 && ! gh release view >/dev/null 2>&1; then
+                echo "tags_releases=fail" >>"$GITHUB_OUTPUT"
+            fi
+        }; :
+      shell: bash
+      id: tags_releases
